version: "3.7"

services:
  pgtyped_postgres:
    container_name: pgtyped_postgres
    image: postgres:14.1
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=password", "pg_isready", "-U", "postgres", "-h", "127.0.0.1", "-p", "5432"]
      interval: 1s
      timeout: 1s
      retries: 10
      start_period: 1s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'pgtyped'
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5434:5432
    expose:
      - '5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/logs:/var/log
